server {
    listen 80;
    server_name _;

    location /p/ {
        root /usr/share/nginx/html;
        try_files $uri /p.html;
    }
    location /cliente {
        root /usr/share/nginx/html;
        try_files $uri /cliente.html;
    }
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri.html $uri/ =404;
    }
}
